[package]
name = "tyto"
version = "0.7.0"
authors = ["Alexander Decurnou <alex@deekerno.com>"]
edition = "2021"

[dependencies]
axum = "0.6"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
urlencoding = "2.1"
